services:
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
            - MYSQL_DATABASE=roundcubemail

    roundcubemail:
        image: roundcube/roundcubemail:latest-fpm
        container_name: roundcubemail
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - www:/var/www/html
            - www:/var/www/html/mail # fucking stupid but this is the least cancer way to trick php into letting me put roundcube in a directory
        environment:
            - ROUNDCUBEMAIL_DB_TYPE=mysql
            - ROUNDCUBEMAIL_DB_HOST=db
            - ROUNDCUBEMAIL_DB_PASSWORD=${SQL_PASSWORD}
            - ROUNDCUBEMAIL_SKIN=elastic
            - ROUNDCUBEMAIL_DEFAULT_HOST=${MAIL_HOST}
            - ROUNDCUBEMAIL_SMTP_SERVER=${MAIL_HOST}

    web:
        image: nginx
        depends_on:
            - roundcubemail
        volumes:
            - ./nginx:/etc/nginx/templates
            - www:/var/www/html/mail
        ports:
            - "80:80"
        environment:
            # - NGINX_HOST=foobar.com
            - NGINX_PORT=80
            - NGINX_PHP_CGI=roundcubemail:9000

volumes:
    db:
    www:

version: "3"
