services:
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
            - MYSQL_DATABASE=roundcubemail

    roundcubemail:
        image: roundcube/roundcubemail:latest-fpm
        container_name: roundcubemail
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - www:/var/www/html
            - www:/var/www/html/mail # fucking stupid but this is the least cancer way to trick php into letting me put roundcube in a directory
        environment:
            - ROUNDCUBEMAIL_DB_TYPE=mysql
            - ROUNDCUBEMAIL_DB_HOST=db
            - ROUNDCUBEMAIL_DB_PASSWORD=${SQL_PASSWORD}
            - ROUNDCUBEMAIL_SKIN=elastic
            - ROUNDCUBEMAIL_DEFAULT_HOST=${MAIL_HOST}
            - ROUNDCUBEMAIL_SMTP_SERVER=${MAIL_HOST}

    web:
        build: webzone
        env_file: .env
        restart: unless-stopped

    kibana:
        image: docker.elastic.co/kibana/kibana:8.5.0
        container_name: kibana
        restart: unless-stopped
        ports:
            - "5601:5601"
        environment:
            - SERVER_BASEPATH="/kibana"
            - KIBANA_FLEET_SETUP='1'
            - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS:-}
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD:-}
            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/http_ca.crt
            - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
        volumes:
            - ./elastic/http_ca.crt:/usr/share/kibana/config/certs/http_ca.crt:ro

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        depends_on:
            - roundcubemail
        volumes:
            - ./nginx:/etc/nginx/templates
            - www:/var/www/html/mail
        ports:
            - "80:80"
        environment:
            # - NGINX_HOST=foobar.com
            - NGINX_PORT=80
            - NGINX_PHP_CGI=roundcubemail:9000

volumes:
    db:
    www:

version: "3"
